name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/SSH_PRIVATE_KEY"
      - run: chmod 600 "$HOME/.ssh/SSH_PRIVATE_KEY"
      # Build
      # - run: npm ci
      # - run: npm run build
      # Deploy
      - name: executing remote ssh commands using password test
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/test-nostr-blog
            git pull origin main
            npm install
            npm run build
            pm2 stop client
            pm2 start client
